# Generated by Django 2.2.16 on 2022-08-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220811_1511'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='core_follow_prevent_self_follow',
        ),
    ]
